version: "3"

services:
  http_api:
      build:
        context: .
        dockerfile: Dockerfile_http_api
      ports:
        - 8080:8080

  snmp_agent:
      build:
        context: .
        dockerfile: Dockerfile_snmp_agent
      ports:
        - 161:161/udp
  dummy_sensor:
    build:
      context: .
      dockerfile: Dockerfile_dummy_sensor
    depends_on:
      - mqtt_broker

  opcua_server:
      build:
        context: .
        dockerfile: Dockerfile_opcua_server
        
  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    - mosquitto_data:/mosquitto/data
    - mosquitto_log:/mosquitto/log

  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - mqtt_broker
      - influxdb

  influxdb:
    image: influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - 8086:8086
   
  modbus-server:
    container_name: modbus-server
    image: oitc/modbus-server
    restart: always
    command: -f /server_config.json
    ports:
      - 5020:5020
    volumes:
      - ./server_config.json:/server_config.json:ro
  
  kafka:
      image: wurstmeister/kafka:latest
      ports:
        - "9092:9092"
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=kafka
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_CREATE_TOPICS=metrics:1:1
      
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  
  kafka-consumer:
    image: wurstmeister/kafka:latest
    command: sleep 10 && bash -c "echo 'Waiting for Kafka to start...'; sleep 10; kafka-console-consumer --bootstrap-server kafka:9092 --topic metrics --from-beginning"
    depends_on:
      - kafka

volumes:
  influxdb_data:
  mosquitto_data:
  mosquitto_log:

